name: Deploy Dist
on: [push, workflow_dispatch] # Run the workflow on these events
# on: # Run the workflow on these events
#     - push
#     - workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              run: |
                echo "Hello, Workflow!"
                echo "${{ toJson(github) }}"
                git clone https://github.com/Viole01/${{ github.repository }}.git